<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import type { FinancialTransactionType } from '@/modules/clinic-data'
const router = useRouter(); const isSaving = ref(false); const errorMessage = ref('')
const form = ref({ type: 'income' as FinancialTransactionType, category: '', description: '', amount: '', occurredOn: new Date().toISOString().slice(0, 10) })
function goBack() { void router.push('/finance') }
async function saveTransaction() { if (!form.value.category.trim() || !form.value.description.trim() || Number(form.value.amount) <= 0 || !form.value.occurredOn) { errorMessage.value = 'أدخل التصنيف والوصف والمبلغ وتاريخ العملية.'; return }; isSaving.value = true; errorMessage.value = ''; try { await window.electronAPI.finance.createTransaction({ transaction_type: form.value.type, category: form.value.category.trim(), description: form.value.description.trim(), amount: Number(form.value.amount), occurred_on: form.value.occurredOn }); await router.push('/finance') } catch (error) { errorMessage.value = error instanceof Error ? error.message : 'تعذر حفظ العملية المالية.' } finally { isSaving.value = false } }
</script>
<template><section class="mx-auto w-full max-w-2xl space-y-6"><header class="border-b border-default pb-5"><UButton icon="i-lucide-arrow-right" color="neutral" variant="ghost" label="الحسابات والمخزون" class="-me-2 mb-3" @click="goBack" /><h1 class="text-2xl font-bold text-highlighted">تسجيل عملية مالية</h1><p class="mt-2 text-sm text-muted">سجل إيراداً أو مصروفاً في حسابات العيادة.</p></header><form class="space-y-5 border border-default bg-default p-5 shadow-sm sm:p-7" @submit.prevent="saveTransaction"><UFormField label="نوع العملية"><USelect v-model="form.type" :items="[{ label: 'إيراد', value: 'income' }, { label: 'مصروف', value: 'expense' }]" class="w-full" /></UFormField><UFormField label="التصنيف" required><UInput v-model="form.category" placeholder="مثل: كشف، رواتب، مستلزمات" class="w-full" autofocus /></UFormField><UFormField label="الوصف" required><UInput v-model="form.description" class="w-full" /></UFormField><div class="grid gap-4 sm:grid-cols-2"><UFormField label="المبلغ (د.ع)" required><UInput v-model="form.amount" type="number" min="0.01" step="0.01" class="w-full" /></UFormField><UFormField label="التاريخ" required><UInput v-model="form.occurredOn" type="date" class="w-full" /></UFormField></div><p v-if="errorMessage" class="text-sm text-error">{{ errorMessage }}</p><div class="flex justify-end gap-2 border-t border-default pt-5"><UButton icon="i-lucide-x" color="neutral" variant="ghost" label="إلغاء" @click="goBack" /><UButton type="submit" :loading="isSaving" label="تسجيل العملية" /></div></form></section></template>
