<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
const router = useRouter(); const isSaving = ref(false); const errorMessage = ref('')
const form = ref({ name: '', sku: '', unit: 'قطعة', quantity: '', reorderLevel: '', unitCost: '' })
function goBack() { void router.push('/finance') }
async function saveItem() { if (!form.value.name.trim() || !form.value.unit.trim() || Number(form.value.reorderLevel || 0) < 0 || Number(form.value.unitCost || 0) < 0 || Number(form.value.quantity || 0) < 0) { errorMessage.value = 'أدخل اسم الصنف ووحدة القياس والكميات بقيم صحيحة.'; return }; isSaving.value = true; errorMessage.value = ''; try { await window.electronAPI.inventory.createItem({ name: form.value.name.trim(), sku: form.value.sku.trim() || null, unit: form.value.unit.trim(), quantity: Number(form.value.quantity || 0), reorder_level: Number(form.value.reorderLevel || 0), unit_cost: Number(form.value.unitCost || 0) }); await router.push('/finance') } catch (error) { errorMessage.value = error instanceof Error ? error.message : 'تعذر حفظ صنف المخزون. تأكد من عدم تكرار رمز الصنف.' } finally { isSaving.value = false } }
</script>
<template><section class="mx-auto w-full max-w-2xl space-y-6"><header class="border-b border-default pb-5"><UButton icon="i-lucide-arrow-right" color="neutral" variant="ghost" label="الحسابات والمخزون" class="-me-2 mb-3" @click="goBack" /><h1 class="text-2xl font-bold text-highlighted">صنف مخزون جديد</h1><p class="mt-2 text-sm text-muted">أضف صنفاً ومخزونه الافتتاحي إلى العيادة.</p></header><form class="space-y-5 border border-default bg-default p-5 shadow-sm sm:p-7" @submit.prevent="saveItem"><UFormField label="اسم الصنف" required><UInput v-model="form.name" class="w-full" autofocus /></UFormField><div class="grid gap-4 sm:grid-cols-2"><UFormField label="رمز الصنف"><UInput v-model="form.sku" class="w-full" dir="ltr" /></UFormField><UFormField label="وحدة القياس" required><UInput v-model="form.unit" class="w-full" /></UFormField></div><div class="grid gap-4 sm:grid-cols-3"><UFormField label="الكمية الافتتاحية"><UInput v-model="form.quantity" type="number" min="0" step="0.01" class="w-full" /></UFormField><UFormField label="حد إعادة الطلب"><UInput v-model="form.reorderLevel" type="number" min="0" step="0.01" class="w-full" /></UFormField><UFormField label="تكلفة الوحدة (د.ع)"><UInput v-model="form.unitCost" type="number" min="0" step="0.01" class="w-full" /></UFormField></div><p v-if="errorMessage" class="text-sm text-error">{{ errorMessage }}</p><div class="flex justify-end gap-2 border-t border-default pt-5"><UButton icon="i-lucide-x" color="neutral" variant="ghost" label="إلغاء" @click="goBack" /><UButton type="submit" icon="i-lucide-package-plus" :loading="isSaving" label="إضافة الصنف" /></div></form></section></template>
