<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import type { InventoryItem, MedicalRecord, Patient } from '@/modules/clinic-data'
const router = useRouter(); const patients = ref<Patient[]>([]); const records = ref<MedicalRecord[]>([]); const inventoryItems = ref<InventoryItem[]>([]); const isSaving = ref(false); const errorMessage = ref('')
const form = ref({ patientId: '', recordId: '', testName: '', urgency: 'routine' as 'routine' | 'urgent', indication: '', inventoryItemId: 'none' })
const inventoryItemItems = computed(() => [{ label: 'بدون ربط بالمخزون', value: 'none' }, ...inventoryItems.value.map((item) => ({ label: `${item.name} (${item.quantity} ${item.unit} متاح)`, value: String(item.id) }))])
function goBack() { void router.push('/labs') }
async function loadRecords() { records.value = form.value.patientId ? (await window.electronAPI.medicalRecords.listByPatient(Number(form.value.patientId))).records : []; if (!records.value.some((record) => String(record.id) === form.value.recordId)) form.value.recordId = records.value[0] ? String(records.value[0].id) : '' }
async function saveOrder() { if (!form.value.patientId || !form.value.recordId || !form.value.testName.trim()) { errorMessage.value = 'اختر المراجع والزيارة وأدخل اسم الفحص.'; return }; isSaving.value = true; errorMessage.value = ''; try { await window.electronAPI.labs.createOrder({ medical_record_id: Number(form.value.recordId), patient_id: Number(form.value.patientId), test_name: form.value.testName.trim(), urgency: form.value.urgency, clinical_indication: form.value.indication.trim(), inventory_item_id: form.value.inventoryItemId !== 'none' ? Number(form.value.inventoryItemId) : null }); await router.push('/labs') } catch (error) { errorMessage.value = error instanceof Error ? error.message : 'تعذر إنشاء طلب الفحص.' } finally { isSaving.value = false } }
watch(() => form.value.patientId, loadRecords)
onMounted(async () => { try { const [patientRows, itemRows] = await Promise.all([window.electronAPI.patients.list(), window.electronAPI.inventory.list()]); patients.value = patientRows; inventoryItems.value = itemRows; form.value.patientId = patients.value[0] ? String(patients.value[0].id) : ''; await loadRecords() } catch (error) { errorMessage.value = error instanceof Error ? error.message : 'تعذر تحميل بيانات الفحص.' } })
</script>
<template><section class="mx-auto w-full max-w-2xl space-y-6"><header class="border-b border-default pb-5"><UButton icon="i-lucide-arrow-right" color="neutral" variant="ghost" label="الفحوصات والتحاليل" class="-me-2 mb-3" @click="goBack" /><h1 class="text-2xl font-bold text-highlighted">طلب فحص جديد</h1><p class="mt-2 text-sm text-muted">اربط الفحص بزيارة موثقة وأدخل سبب الطلب.</p></header><form class="space-y-5 border border-default bg-default p-5 shadow-sm sm:p-7" @submit.prevent="saveOrder"><UFormField label="المراجع" required><USelect v-model="form.patientId" :items="patients.map((patient) => ({ label: `${patient.full_name} - ${patient.phone}`, value: String(patient.id) }))" class="w-full" /></UFormField><UFormField label="الزيارة الموثقة" required><USelect v-model="form.recordId" :items="records.map((record) => ({ label: `${new Intl.DateTimeFormat('ar-SA', { dateStyle: 'medium' }).format(new Date(record.visit_date))}${record.diagnosis ? ` - ${record.diagnosis}` : ''}`, value: String(record.id) }))" placeholder="اختر زيارة" class="w-full" :disabled="!form.patientId" /></UFormField><UFormField label="اسم الفحص" required><UInput v-model="form.testName" class="w-full" autofocus /></UFormField><UFormField label="الأولوية"><USelect v-model="form.urgency" :items="[{ label: 'روتيني', value: 'routine' }, { label: 'عاجل', value: 'urgent' }]" class="w-full" /></UFormField><UFormField label="صنف المخزون" description="عند الاختيار، تُخصم وحدة واحدة من المخزون وتُسجَّل كإيراد على حساب المراجع."><USelect v-model="form.inventoryItemId" :items="inventoryItemItems" class="w-full" /></UFormField><UFormField label="السبب السريري"><UTextarea v-model="form.indication" class="w-full" /></UFormField><p v-if="errorMessage" class="text-sm text-error">{{ errorMessage }}</p><div class="flex justify-end gap-2 border-t border-default pt-5"><UButton icon="i-lucide-x" color="neutral" variant="ghost" label="إلغاء" @click="goBack" /><UButton type="submit" icon="i-lucide-flask-conical" :loading="isSaving" label="إنشاء الطلب" /></div></form></section></template>
