<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import type { MedicalRecord, Patient, PrescriptionStatus } from '@/modules/clinic-data'
type Medicine = { medicineName: string; dosage: string; frequency: string; durationDays: string; notes: string }
const route = useRoute(); const router = useRouter(); const patients = ref<Patient[]>([]); const records = ref<MedicalRecord[]>([]); const isSaving = ref(false); const errorMessage = ref('')
const form = ref({ patientId: String(route.query.patientId || ''), recordId: String(route.query.recordId || ''), medicines: [{ medicineName: '', dosage: '', frequency: '', durationDays: '', notes: '' }] as Medicine[], status: 'active' as PrescriptionStatus })
const statusItems = [{ label: 'نشطة', value: 'active' }, { label: 'تم الصرف', value: 'fulfilled' }, { label: 'ملغاة', value: 'cancelled' }]
const validMedicines = computed(() => form.value.medicines.filter((medicine) => medicine.medicineName.trim() && medicine.dosage.trim() && medicine.frequency.trim()))
function goBack() { void router.push('/prescriptions') }
async function loadRecords() { records.value = form.value.patientId ? (await window.electronAPI.medicalRecords.listByPatient(Number(form.value.patientId))).records : []; if (!records.value.some((record) => String(record.id) === form.value.recordId)) form.value.recordId = records.value[0] ? String(records.value[0].id) : '' }
function addMedicine() { form.value.medicines.push({ medicineName: '', dosage: '', frequency: '', durationDays: '', notes: '' }) }
function removeMedicine(index: number) { if (form.value.medicines.length > 1) form.value.medicines.splice(index, 1) }
async function savePrescription() { if (!form.value.patientId || !form.value.recordId || !validMedicines.value.length) { errorMessage.value = 'اختر المراجع والزيارة وأدخل اسم الدواء والجرعة والتكرار.'; return }; isSaving.value = true; errorMessage.value = ''; try { await Promise.all(validMedicines.value.map((medicine) => window.electronAPI.prescriptions.create({ medical_record_id: Number(form.value.recordId), patient_id: Number(form.value.patientId), medicine_name: medicine.medicineName.trim(), dosage: medicine.dosage.trim(), frequency: medicine.frequency.trim(), duration_days: medicine.durationDays ? Number(medicine.durationDays) : null, notes: medicine.notes.trim(), status: form.value.status }))); await router.push('/prescriptions') } catch (error) { errorMessage.value = error instanceof Error ? error.message : 'تعذر حفظ الوصفة.' } finally { isSaving.value = false } }
watch(() => form.value.patientId, loadRecords)
onMounted(async () => { try { patients.value = await window.electronAPI.patients.list(); if (!form.value.patientId) form.value.patientId = patients.value[0] ? String(patients.value[0].id) : ''; await loadRecords() } catch (error) { errorMessage.value = error instanceof Error ? error.message : 'تعذر تحميل بيانات الوصفة.' } })
</script>
<template><section class="mx-auto w-full max-w-4xl space-y-6"><header class="border-b border-default pb-5"><UButton icon="i-lucide-arrow-right" color="neutral" variant="ghost" label="الوصفات الطبية" class="-me-2 mb-3" @click="goBack" /><h1 class="text-2xl font-bold text-highlighted">وصفة طبية جديدة</h1><p class="mt-2 text-sm text-muted">أضف دواءً أو أكثر إلى زيارة المراجع.</p></header><form class="space-y-5 border border-default bg-default p-5 shadow-sm sm:p-7" @submit.prevent="savePrescription"><div class="grid gap-4 sm:grid-cols-2"><UFormField label="المراجع" required><USelect v-model="form.patientId" :items="patients.map((patient) => ({ label: `${patient.full_name} - ${patient.phone}`, value: String(patient.id) }))" class="w-full" /></UFormField><UFormField label="تاريخ الزيارة" required><USelect v-model="form.recordId" :items="records.map((record) => ({ label: `${new Intl.DateTimeFormat('ar-SA', { dateStyle: 'medium' }).format(new Date(record.visit_date))}${record.diagnosis ? ` - ${record.diagnosis}` : ''}`, value: String(record.id) }))" placeholder="اختر الزيارة المرتبطة" class="w-full" :disabled="!form.patientId || !records.length" /></UFormField></div><div class="space-y-3 border-t border-default pt-4"><div class="flex items-center justify-between"><h2 class="font-semibold text-highlighted">الأدوية الموصوفة ({{ form.medicines.length }})</h2><UButton icon="i-lucide-plus" color="primary" variant="ghost" size="sm" label="إضافة دواء آخر" @click="addMedicine" /></div><div v-for="(medicine, index) in form.medicines" :key="index" class="space-y-3 border border-default bg-muted/20 p-4"><div class="flex items-center justify-between"><span class="text-xs font-bold text-primary">دواء #{{ index + 1 }}</span><UButton v-if="form.medicines.length > 1" icon="i-lucide-trash-2" color="error" variant="ghost" size="xs" aria-label="حذف الدواء" @click="removeMedicine(index)" /></div><div class="grid gap-3 sm:grid-cols-2"><UFormField label="اسم الدواء" required><UInput v-model="medicine.medicineName" /></UFormField><UFormField label="الجرعة" required><UInput v-model="medicine.dosage" /></UFormField><UFormField label="التكرار" required><UInput v-model="medicine.frequency" /></UFormField><UFormField label="المدة بالأيام"><UInput v-model="medicine.durationDays" type="number" min="1" /></UFormField><UFormField label="تعليمات الاستخدام" class="sm:col-span-2"><UInput v-model="medicine.notes" /></UFormField></div></div></div><UFormField label="حالة الوصفة"><USelect v-model="form.status" :items="statusItems" /></UFormField><p v-if="errorMessage" class="text-sm text-error">{{ errorMessage }}</p><div class="flex justify-end gap-2 border-t border-default pt-5"><UButton icon="i-lucide-x" color="neutral" variant="ghost" label="إلغاء" @click="goBack" /><UButton type="submit" icon="i-lucide-save" :loading="isSaving" :disabled="!validMedicines.length" label="حفظ الوصفة" /></div></form></section></template>
